<a href="https://colab.research.google.com/github/shreekantpatel1/shreekantpatel1/blob/main/labs/lab6/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv", delimiter=',', header=None, na_values=[99.00], names=np.arange(1, 101))

In [3]:
len(df)

24983

In [4]:
#df.drop([0,], axis=1, inplace=True)
df.head()

1     2     3     4     5     6     7     8     9     10   ...   91   \
74.0  -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76  ...  2.82   
100.0  4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...  2.82   
49.0    NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN   NaN  ...   NaN   
48.0    NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  1.84  ...   NaN   
91.0   8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...  5.19   

        92    93    94    95    96    97    98    99    100  
74.0    NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
100.0 -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
49.0    NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
48.0    NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
91.0   5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  

[5 rows x 100 columns]

In [5]:
df.iloc[3,2]

nan

In [6]:
df.iloc[5924 ,82]

-3.98

In [7]:
np.argmin(df.mean(axis=0))

57

In [8]:
df.replace(np.NaN, 0, inplace=True)

In [9]:
df.describe()

1             2             3             4             5    \
count  24983.000000  24983.000000  24983.000000  24983.000000  24983.000000   
mean       0.595687      0.151728      0.210881     -0.905326      0.403460   
std        4.218722      4.776192      4.409642      4.196537      5.255073   
min       -9.950000     -9.950000     -9.950000     -9.950000     -9.950000   
25%       -0.150000     -2.180000     -1.145000     -3.350000     -3.690000   
50%        0.000000      0.000000      0.000000      0.000000      1.120000   
75%        3.135000      3.250000      2.720000      0.000000      4.470000   
max        9.370000      9.370000      9.370000      9.370000      9.370000   

                6             7             8             9             10   \
count  24983.000000  24983.000000  24983.000000  24983.000000  24983.000000   
mean       1.303933     -0.429542     -0.624035     -0.351213      1.058568   
std        4.474178      5.495165      4.928950      4.107803      4.616428   
min       -9.950000     -9.950000     -9.950000     -9.950000     -9.950000   
25%       -0.390000     -5.290000     -4.610000     -1.775000     -0.830000   
50%        0.730000     -0.050000     -0.290000      0.000000      0.290000   
75%        4.660000      3.880000      3.060000      1.260000      4.470000   
max        9.470000      9.610000      9.760000      9.900000      9.370000   

       ...           91            92            93            94   \
count  ...  24983.000000  24983.000000  24983.000000  24983.000000   
mean   ...      0.789202      0.466977      1.001095      0.479107   
std    ...      3.301422      3.276923      3.163146      3.334650   
min    ...     -9.950000     -9.950000     -9.950000     -9.950000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      0.780000      0.000000      1.750000      0.150000   
max    ...      9.560000      9.420000      9.370000      9.420000   

                95            96            97            98            99   \
count  24983.000000  24983.000000  24983.000000  24983.000000  24983.000000   
mean       0.426957      0.634247      0.704793      0.327751     -0.013644   
std        3.351201      3.215344      3.363833      3.544630      3.420938   
min       -9.950000     -9.950000     -9.950000     -9.950000     -9.950000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.100000      0.870000      1.120000      0.000000      0.000000   
max        9.370000      9.370000      9.370000      9.370000      9.370000   

                100  
count  24983.000000  
mean       0.539162  
std        3.408862  
min       -9.950000  
25%        0.000000  
50%        0.000000  
75%        0.100000  
max        9.370000  

[8 rows x 100 columns]

In [10]:
np.argmin(np.mean(df, axis=0))


15

In [29]:
data = pd.read_excel("movies_latent_factors.xlsx")

In [30]:
data['Movie ID'] = data['Movie ID'].astype(int)

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Movie ID  100 non-null    int64  
 1   Title     100 non-null    object 
 2   Factor1   100 non-null    float64
 3   Factor2   100 non-null    float64
 4   Factor3   100 non-null    float64
 5   Factor4   100 non-null    float64
 6   Factor5   100 non-null    float64
 7   Factor6   100 non-null    float64
 8   Factor7   100 non-null    float64
 9   Factor8   100 non-null    float64
 10  Factor9   100 non-null    float64
 11  Factor10  100 non-null    float64
 12  Factor11  100 non-null    float64
 13  Factor12  100 non-null    float64
 14  Factor13  100 non-null    float64
 15  Factor14  100 non-null    float64
 16  Factor15  100 non-null    float64
dtypes: float64(15), int64(1), object(1)
memory usage: 13.4+ KB


In [17]:
data.loc[data['Movie ID'] == 63, 'Factor10']

7   -0.041067
Name: Factor10, dtype: float64

In [18]:
#dot product between movie id and user 
# transpose any one of it

#[1 2] dot [1
#           2] = 1 + 4 = 5, 5 is prediction 

In [130]:
a = [1, 2]
b = [1, 2]
np.dot(a, b)

5

In [25]:
h_r = data['Factor11']
np.max(h_r)

3.070518299945125

In [142]:
d2 = xls = pd.ExcelFile("movies_latent_factors.xlsx")
dfm = pd.read_excel(xls, 'Items', index_col=0)
dfu = pd.read_excel(xls, 'Users', index_col=0)

In [143]:
u = dfu.loc[4768]

In [144]:
u =np.array(u[:])
u

array([-0.20402409,  0.16107871, -0.0904475 ,  0.13849453, -0.16293366,
        0.1638944 ,  0.05150182, -0.08858222,  0.126829  ,  0.06596709,
        0.08500812,  0.35540448,  0.007108  , -0.1186634 , -0.03912536])

In [145]:
i = dfm.loc[672]
i

Title       Harry Potter and the Chamber of Secrets (2002)
Factor1                                           1.302389
Factor2                                          -1.582413
Factor3                                           1.664079
Factor4                                           1.234164
Factor5                                           0.631764
Factor6                                           -2.23746
Factor7                                          -0.025302
Factor8                                           0.262009
Factor9                                           0.225579
Factor10                                         -2.380327
Factor11                                          2.792338
Factor12                                           2.55065
Factor13                                          0.867521
Factor14                                         -0.047426
Factor15                                          0.336602
Name: 672, dtype: object

In [146]:
i = np.array(i[1:], dtype=np.double)
i

array([ 1.30238897, -1.58241343,  1.66407885,  1.23416382,  0.63176394,
       -2.23746023, -0.02530225,  0.26200933,  0.22557946, -2.38032708,
        2.79233767,  2.55064998,  0.86752118, -0.04742643,  0.33660215])

In [147]:
np.dot(u, i)

0.019741054831505192

In [148]:
u = dfu.loc[3806]
u =np.array(u[:])
u

array([-0.04234433, -0.04075545, -0.05571989, -0.07372552,  0.01820304,
        0.09194021,  0.12395867, -0.1574026 , -0.02038777,  0.08249335,
        0.22305742, -0.04091509, -0.1303082 , -0.02181588,  0.03454886])

In [149]:
i = dfm.loc[672]
i = np.array(i[1:], dtype=np.double)
i

array([ 1.30238897, -1.58241343,  1.66407885,  1.23416382,  0.63176394,
       -2.23746023, -0.02530225,  0.26200933,  0.22557946, -2.38032708,
        2.79233767,  2.55064998,  0.86752118, -0.04742643,  0.33660215])

In [150]:
np.dot(u, i)

-0.19580828676526094